services:
  mysql:
    image: mysql:8.0.43
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: {$MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: {$MYSQL_DATABASE}
      MYSQL_USER: {$MYSQL_USER}
      MYSQL_PASSWORD: {$MYSQL_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci"
      ]

  redis:
    image: redis:7.4-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command:
      - redis-server
      - --requirepass
      - local-dev-redis-password-cheket-d108
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec
      - --maxmemory
      - 256mb
      - --maxmemory-policy
      - allkeys-lru

volumes:
  mysql_data:
  redis_data: