plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.11'
	id 'io.spring.dependency-management' version '1.1.7'
    id 'checkstyle'
    id 'com.diffplug.spotless' version '6.25.0'
}

group = 'com.ssafy'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.16'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'org.web3j:core:4.12.3' // Web3j 의존성 추가
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6' // JJWT 의존성 추가
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6' // JJWT 의존성 추가
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6' // JJWT 의존성 추가
    implementation 'net.nurigo:sdk:4.3.0'
    implementation 'software.amazon.awssdk:s3:2.25.8'
}

tasks.named('test') {
	useJUnitPlatform()
}

spotless {
    lineEndings 'UNIX'

    java {
        eclipse().configFile('config/formatter/eclipse-java-formatter.xml')
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
    format 'misc', {
        target '*.gradle', '*.md', '.gitignore'
        trimTrailingWhitespace()
        endWithNewline()
    }
}

checkstyle {
    toolVersion = '10.12.5'
    configFile = file('config/checkstyle/checkstyle.xml')
    maxWarnings = 0
    ignoreFailures = false
}

tasks.named('check') {
    dependsOn 'spotlessCheck'
}
