services:
  host-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: https://j14d108.p.ssafy.io
    container_name: cheket_host_web
    environment:
      TZ: Asia/Seoul
      COLLECTION_PREVIEW_URL: http://cheket_collection:3100/preview
    ports:
      - "3000:3000"
    restart: unless-stopped

  customer-collection:
    build:
      context: ../customer-collection
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: https://j14d108.p.ssafy.io
    container_name: cheket_collection
    environment:
      TZ: Asia/Seoul
    ports:
      - "3100:3100"
    restart: unless-stopped
